import type { Route } from '../types';

export const generateGPX = (route: Route): string => {
  const timestamp = new Date().toISOString();
  const name = `RunAnyWay - ${route.distance.toFixed(1)}km`;
  const desc = `Generated by RunAnyWay - https://runanyway.vercel.app/`;

  const gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="RunAnyWay Code" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata>
    <name>${name}</name>
    <desc>${desc}</desc>
    <time>${timestamp}</time>
  </metadata>
  <trk>
    <name>${name}</name>
    <desc>${desc}</desc>
    <trkseg>
      ${route.coordinates.map(coord => `<trkpt lat="${coord.lat}" lon="${coord.lng}"></trkpt>`).join('\n      ')}
    </trkseg>
  </trk>
</gpx>`;

  return gpx;
};

export const downloadGPX = (route: Route) => {
  const gpxContent = generateGPX(route);
  const blob = new Blob([gpxContent], { type: 'application/gpx+xml' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `runanyway-${new Date().toISOString().slice(0, 10)}.gpx`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
